name: tech_blog
description: "content sharing platform"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  hugeicons: ^0.0.7
  flutter_svg: ^2.0.10+1
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # example:
  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_gen:
  integrations:
    flutter_svg: true
